In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('Global_Mobility_Report.csv')

/var/folders/__/8q6wtgc10gsdhs_z1lv_0r700000gn/T/ipykernel_3180/3541448081.py:1: DtypeWarning: Columns (3,4,5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('Global_Mobility_Report.csv')

In [6]:
united_states = df[df['country_region'] == 'United States']
united_states.head()

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,place_id,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
9104472,US,United States,NaN,NaN,NaN,NaN,NaN,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-15,6.0,2.0,15.0,3.0,2.0,-1.0
9104473,US,United States,NaN,NaN,NaN,NaN,NaN,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-16,7.0,1.0,16.0,2.0,0.0,-1.0
9104474,US,United States,NaN,NaN,NaN,NaN,NaN,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-17,6.0,0.0,28.0,-9.0,-24.0,5.0
9104475,US,United States,NaN,NaN,NaN,NaN,NaN,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-18,0.0,-1.0,6.0,1.0,0.0,1.0
9104476,US,United States,NaN,NaN,NaN,NaN,NaN,ChIJCzYy5IS16lQRQrfeQ5K5Oxw,2020-02-19,2.0,0.0,8.0,1.0,1.0,0.0

In [8]:
california_counties = united_states[united_states['sub_region_1'] == 'California']

In [9]:
california_counties.head()

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,place_id,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
9253444,US,United States,California,NaN,NaN,US-CA,NaN,ChIJPV4oX_65j4ARVW8IJ6IJUYs,2020-02-15,1.0,1.0,19.0,1.0,-1.0,0.0
9253445,US,United States,California,NaN,NaN,US-CA,NaN,ChIJPV4oX_65j4ARVW8IJ6IJUYs,2020-02-16,5.0,0.0,31.0,1.0,-1.0,-1.0
9253446,US,United States,California,NaN,NaN,US-CA,NaN,ChIJPV4oX_65j4ARVW8IJ6IJUYs,2020-02-17,9.0,1.0,44.0,-12.0,-38.0,8.0
9253447,US,United States,California,NaN,NaN,US-CA,NaN,ChIJPV4oX_65j4ARVW8IJ6IJUYs,2020-02-18,0.0,0.0,16.0,3.0,0.0,0.0
9253448,US,United States,California,NaN,NaN,US-CA,NaN,ChIJPV4oX_65j4ARVW8IJ6IJUYs,2020-02-19,0.0,0.0,13.0,1.0,0.0,0.0

In [10]:
california_counties.to_csv('California_Counties.csv')